apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-project
  template:
    metadata:
      labels:
        app: java-project
    spec:
      containers:
      - name: java-app-container
        image: javaproject.azurecr.io/project:${{ github.sha }}
        ports:
        - containerPort: 8080
