apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-project-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-project
  template:
    metadata:
      labels:
        app: java-project
    spec:
      containers:
      - name: java-project-container
        image: javaproject.azurecr.io/project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
    strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
