apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-project-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-project
  template:
    metadata:
      labels:
        app: java-project
    spec:
      containers:
      - name: java-project-container
        image: javaproject.azurecr.io/project:latest
        ports:
        - containerPort: 80
